# Generated by Django 5.0.6 on 2024-11-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_producto_alter_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('consignacion', 'Consignación'), ('venta_paga', 'Venta por Paga')], default='venta_paga', max_length=20),
        ),
    ]
